language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nityaprashant/react-test -f ./client/dockerfile.dev ./client

script:
   - docker run -e CI=true nityaprashant/react-test npm test

after_sucess:
  - docker build -t nityaprashant/multi-client -f ./client
  - docker build -t nityaprashant/multi-nginx -f ./nginx
  - docker build -t nityaprashant/multi-server -f ./server
  - docker build -t nityaprashant/multi-worker -f ./worker
