sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t nityatesting/react-test -f ./client/dockerfile.dev ./client

script:
   - docker run -e CI=true nityatesting/react-test npm test

after_sucess:
  - docker build -t nityatesting/multi-client ./client
  - docker build -t nityatesting/multi-nginx ./nginx
  - docker build -t nityatesting/multi-server ./server
  - docker build -t nityatesting/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

#take those images and push to docker hub
  - docker push nityatesting/multi-client
  - docker push nityatesting/multi-nginx
  - docker push nityatesting/multi-server
  - docker push nityatesting/multi-worker